<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Brand::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $brands = [
            ['name' => '1 SPOT',           'classification' => 'Tech',            'description' => 'Power supply solutions for pedalboards and effects'],
            ['name' => '2ND HAND',          'classification' => 'Tech',            'description' => 'Pre-owned and refurbished tech equipment'],
            ['name' => '7ARTISANS',         'classification' => 'Both',            'description' => 'Affordable manual prime lenses for mirrorless cameras'],
            ['name' => 'ACASIS',            'classification' => 'Tech',            'description' => 'USB hubs, docking stations, and storage accessories'],
            ['name' => 'ACCSOON',           'classification' => 'Tech',            'description' => 'Wireless video transmission systems for filmmakers'],
            ['name' => 'ACURITE',           'classification' => 'Tech',            'description' => 'Precision weather and environmental monitoring instruments'],
            ['name' => 'AD-LINK',           'classification' => 'Tech',            'description' => 'Industrial computing and embedded systems'],
            ['name' => 'ADAM AUDIO',        'classification' => 'Tech',            'description' => 'Professional studio monitor speakers'],
            ['name' => 'ADATA',             'classification' => 'Tech',            'description' => 'Memory cards, SSDs, and flash storage solutions'],
            ['name' => 'AGFAPHOTO',         'classification' => 'Design/Consumer', 'description' => 'Film cameras, instant cameras, and photo accessories'],
            ['name' => 'ALCATEL',           'classification' => 'Tech',            'description' => 'Mobile phones and networking equipment'],
            ['name' => 'ALESIS',            'classification' => 'Tech',            'description' => 'Electronic drums, MIDI controllers, and audio gear'],
            ['name' => 'ALLEN & HEATH',     'classification' => 'Tech',            'description' => 'Professional mixing consoles for live and studio'],
            ['name' => 'ALSEYE',            'classification' => 'Tech',            'description' => 'CPU coolers and PC thermal management solutions'],
            ['name' => 'ALTO',              'classification' => 'Tech',            'description' => 'Powered PA speakers, mixers, and live sound equipment'],
            ['name' => 'AMAZON',            'classification' => 'Design/Consumer', 'description' => 'Consumer electronics and smart home devices'],
            ['name' => 'AMD',               'classification' => 'Design/Consumer', 'description' => 'Processors, graphics cards, and computing platforms'],
            ['name' => 'ANDBON',            'classification' => 'Tech',            'description' => 'Camera dry cabinets and humidity-controlled storage'],
            ['name' => 'ANKER',             'classification' => 'Design/Consumer', 'description' => 'Charging accessories, power banks, and audio gear'],
            ['name' => 'ANOVA',             'classification' => 'Design/Consumer', 'description' => 'Smart kitchen appliances and precision cookers'],
            ['name' => 'APRICORN',          'classification' => null,              'description' => 'Encrypted and secure portable storage drives'],
            ['name' => 'APUTURE',           'classification' => 'Tech',            'description' => 'Professional LED lighting for film and photography'],
            ['name' => 'ARGOX',             'classification' => 'Tech',            'description' => 'Barcode printers and label printing solutions'],
            ['name' => 'ASTRHORI',          'classification' => 'Both',            'description' => 'Cinema lenses and photography accessories'],
            ['name' => 'ASUS',              'classification' => 'Design/Consumer', 'description' => 'Laptops, monitors, motherboards, and PC peripherals'],
            ['name' => 'ATOMOS',            'classification' => 'Design/Consumer', 'description' => 'Field recorders, monitors, and video production tools'],
            ['name' => 'AUDTECH',           'classification' => 'Design/Consumer', 'description' => 'Audio accessories and consumer sound equipment'],
            ['name' => 'AVMATRIX',          'classification' => 'Tech',            'description' => 'Video switchers, scalers, and broadcast equipment'],
            ['name' => 'BAOFENG',           'classification' => 'Both',            'description' => 'Portable two-way radios and walkie-talkies'],
            ['name' => 'BASEUS',            'classification' => 'Design/Consumer', 'description' => 'Charging cables, hubs, and mobile accessories'],
            ['name' => 'BEHRINGER',         'classification' => 'Design/Consumer', 'description' => 'Audio mixers, interfaces, and studio equipment'],
            ['name' => 'BELKIN',            'classification' => 'Design/Consumer', 'description' => 'Phone accessories, chargers, and connectivity gear'],
            ['name' => 'BENETECH',          'classification' => 'Tech',            'description' => 'Measurement instruments and digital testing tools'],
            ['name' => 'BENRO',             'classification' => 'Tech',            'description' => 'Tripods, monopods, and camera support systems'],
            ['name' => 'BLACKMAGIC',        'classification' => 'Tech',            'description' => 'Cinema cameras, video production, and color grading tools'],
            ['name' => 'BLAZAR',            'classification' => 'Both',            'description' => 'Anamorphic lenses and cinema accessories'],
            ['name' => 'BLUE',              'classification' => 'Both',            'description' => 'USB microphones, headphones, and streaming audio gear'],
            ['name' => 'BLUETTI',           'classification' => 'Both',            'description' => 'Portable power stations and solar power solutions'],
            ['name' => 'BOSTON ENG.',       'classification' => 'Tech',            'description' => 'Industrial and precision engineering equipment'],
            ['name' => 'BOYA',              'classification' => 'Both',            'description' => 'Wireless lavalier mics and video microphones'],
            ['name' => 'BRINNO',            'classification' => 'Tech',            'description' => 'Time-lapse cameras for construction and security'],
            ['name' => 'CAME-TV',           'classification' => 'Tech',            'description' => 'Camera gimbals, sliders, and production support gear'],
            ['name' => 'CAMP SNAP',         'classification' => 'Design/Consumer', 'description' => 'Simple digital cameras for kids and outdoor adventures'],
            ['name' => 'CANON',             'classification' => 'Both',            'description' => 'Cameras, lenses, and professional imaging equipment'],
            ['name' => 'CAROL',             'classification' => 'Both',            'description' => 'Audio cables, connectors, and signal accessories'],
            ['name' => 'CASIO',             'classification' => 'Both',            'description' => 'Cameras, calculators, watches, and electronics'],
            ['name' => 'CHERRY',            'classification' => 'Both',            'description' => 'Mechanical keyboards and PC input devices'],
            ['name' => 'CHUZHAO',           'classification' => 'Design/Consumer', 'description' => 'Photography lighting and studio accessories'],
            ['name' => 'CINEPRO',           'classification' => 'Tech',            'description' => 'Professional video and cinema production equipment'],
            ['name' => 'CORSAIR',           'classification' => 'Design/Consumer', 'description' => 'Gaming peripherals, memory, and PC components'],
            ['name' => 'CREATIVE',          'classification' => 'Design/Consumer', 'description' => 'Sound cards, USB speakers, and PC audio gear'],
            ['name' => 'CREMONA',           'classification' => 'Both',            'description' => 'Classical and acoustic string instruments'],
            ['name' => 'CROWN',             'classification' => 'Both',            'description' => 'Professional power amplifiers for live sound'],
            ['name' => 'CRUCIAL',           'classification' => 'Both',            'description' => 'RAM, SSDs, and memory upgrades for computers'],
            ['name' => 'D ADDARIO',         'classification' => 'Design/Consumer', 'description' => 'Guitar strings, accessories, and musician supplies'],
            ['name' => 'DATACOLOR',         'classification' => 'Both',            'description' => 'Color calibration tools and monitor profiling devices'],
            ['name' => 'DATASHUR',          'classification' => 'Tech',            'description' => 'PIN-protected encrypted USB flash drives'],
            ['name' => 'DAYTECH',           'classification' => 'Tech',            'description' => 'Video doorbells, security cameras, and smart home devices'],
            ['name' => 'DEARKOL',           'classification' => 'Tech',            'description' => 'Camera and phone mount accessories'],
            ['name' => 'DEITY',             'classification' => 'Tech',            'description' => 'Professional microphones and wireless audio systems'],
            ['name' => 'DELUX',             'classification' => 'Tech',            'description' => 'Ergonomic mice, keyboards, and office peripherals'],
            ['name' => 'DESVIEW',           'classification' => 'Tech',            'description' => 'On-camera field monitors for video production'],
            ['name' => 'DJI',               'classification' => 'Design/Consumer', 'description' => 'Drones, gimbals, and aerial imaging systems'],
            ['name' => 'DOGCARE',           'classification' => 'Both',            'description' => 'Pet tracking and smart pet care devices'],
            ['name' => 'DYMO',              'classification' => 'Tech',            'description' => 'Label makers and label printing solutions'],
            ['name' => 'EAGLETECH',         'classification' => 'Tech',            'description' => 'PC peripherals and computer accessories'],
            ['name' => 'EBL',               'classification' => 'Both',            'description' => 'Rechargeable batteries and smart battery chargers'],
            ['name' => 'ECOFLOW',           'classification' => 'Both',            'description' => 'Portable power stations and solar charging solutions'],
            ['name' => 'EIKON',             'classification' => 'Both',            'description' => 'Professional tattoo machines and supplies'],
            ['name' => 'EIRMAI',            'classification' => 'Both',            'description' => 'Camera dry cabinets and humidity-controlled storage'],
            ['name' => 'EKSA',              'classification' => 'Both',            'description' => 'Gaming headsets and communication audio gear'],
            ['name' => 'ENELOOP',           'classification' => 'Tech',            'description' => 'High-performance rechargeable AA and AAA batteries'],
            ['name' => 'EPIPHONE',          'classification' => 'Design/Consumer', 'description' => 'Electric and acoustic guitars and bass guitars'],
            ['name' => 'EPSON',             'classification' => 'Design/Consumer', 'description' => 'Photo printers, projectors, and imaging devices'],
            ['name' => 'ERGOTRON',          'classification' => 'Design/Consumer', 'description' => 'Monitor arms, desk mounts, and ergonomic workspace solutions'],
            ['name' => 'ERNIE BALL',        'classification' => 'Design/Consumer', 'description' => 'Guitar strings, straps, and musician accessories'],
            ['name' => 'ESCURA',            'classification' => 'Design/Consumer', 'description' => 'Retro-style instant and film cameras'],
            ['name' => 'ESSAGER',           'classification' => 'Design/Consumer', 'description' => 'Charging cables, adapters, and mobile accessories'],
            ['name' => 'EVOLUENT',          'classification' => 'Both',            'description' => 'Vertical ergonomic mice for RSI prevention'],
            ['name' => 'EYOYO',             'classification' => 'Both',            'description' => 'Portable monitors and barcode scanning devices'],
            ['name' => 'FALCAM',            'classification' => 'Tech',            'description' => 'Quick-release camera mounting systems'],
            ['name' => 'FBT',               'classification' => 'Design/Consumer', 'description' => 'Professional PA and loudspeaker systems'],
            ['name' => 'FEELWIND',          'classification' => 'Tech',            'description' => 'Portable fans and personal cooling devices'],
            ['name' => 'FEELWORLD',         'classification' => 'Tech',            'description' => 'Field monitors and on-camera monitors for video work'],
            ['name' => 'FEIYUTECH',         'classification' => 'Design/Consumer', 'description' => 'Camera gimbals and stabilizers for photo and video'],
            ['name' => 'FENDER',            'classification' => 'Design/Consumer', 'description' => 'Electric guitars, bass guitars, and amplifiers'],
            ['name' => 'FERNANDO',          'classification' => 'Design/Consumer', 'description' => 'Classical and acoustic guitars'],
            ['name' => 'FIFINE',            'classification' => 'Design/Consumer', 'description' => 'USB and XLR microphones for streaming and podcasting'],
            ['name' => 'FOCUSRITE',         'classification' => 'Tech',            'description' => 'Audio interfaces and studio recording equipment'],
            ['name' => 'FUJIFILM',          'classification' => 'Both',            'description' => 'Cameras, instant film, and professional imaging'],
            ['name' => 'FUJITSU',           'classification' => 'Design/Consumer', 'description' => 'Storage solutions, scanners, and enterprise electronics'],
            ['name' => 'GIBRALTAR',         'classification' => 'Design/Consumer', 'description' => 'Drum hardware, stands, and percussion accessories'],
            ['name' => 'GIGABYTE',          'classification' => 'Design/Consumer', 'description' => 'Motherboards, graphics cards, and gaming peripherals'],
            ['name' => 'GLIDE GEAR',        'classification' => 'Tech',            'description' => 'Camera sliders, teleprompters, and video rigs'],
            ['name' => 'GODOX',             'classification' => 'Tech',            'description' => 'Studio flash, speedlights, and LED video lighting'],
            ['name' => 'GOLDTOUCH',         'classification' => 'Both',            'description' => 'Ergonomic keyboards and mice for comfortable typing'],
            ['name' => 'GOODWAY',           'classification' => 'Design/Consumer', 'description' => 'Cables, connectors, and signal distribution accessories'],
            ['name' => 'GOPRO',             'classification' => 'Design/Consumer', 'description' => 'Rugged action cameras and mounting accessories'],
            ['name' => 'GREENLEE',          'classification' => 'Both',            'description' => 'Professional electrical and networking tools'],
            ['name' => 'GREENWON',          'classification' => 'Both',            'description' => 'Environmental and food safety testing instruments'],
            ['name' => 'GRETSCH',           'classification' => 'Design/Consumer', 'description' => 'Drums, guitars, and professional musical instruments'],
            ['name' => 'GUMDROP',           'classification' => 'Design/Consumer', 'description' => 'Rugged protective cases for tablets and laptops'],
            ['name' => 'GVM',               'classification' => 'Tech',            'description' => 'LED video lighting panels and photography lights'],
            ['name' => 'HARMAN',            'classification' => 'Design/Consumer', 'description' => 'Premium audio brands including JBL and AKG'],
            ['name' => 'HENGLIXIN',         'classification' => 'Both',            'description' => 'Camera batteries and power accessories'],
            ['name' => 'HERCULES',          'classification' => 'Design/Consumer', 'description' => 'Guitar, keyboard, and instrument display stands'],
            ['name' => 'HIKVISION',         'classification' => 'Design/Consumer', 'description' => 'Security cameras and surveillance systems'],
            ['name' => 'HINISO',            'classification' => 'Tech',            'description' => 'Photography accessories and camera mounts'],
            ['name' => 'HOHEM',             'classification' => 'Design/Consumer', 'description' => 'Smartphone and camera gimbals for stable footage'],
            ['name' => 'HOLLYLAND',         'classification' => 'Tech',            'description' => 'Wireless video and intercom communication systems'],
            ['name' => 'HOSA',              'classification' => 'Design/Consumer', 'description' => 'Audio cables, adapters, and signal accessories'],
            ['name' => 'HOYA',              'classification' => 'Tech',            'description' => 'Camera filters, lens coatings, and optical accessories'],
            ['name' => 'HUAWEI',            'classification' => 'Design/Consumer', 'description' => 'Smartphones, laptops, and networking equipment'],
            ['name' => 'HYPERX',            'classification' => 'Design/Consumer', 'description' => 'Gaming headsets, keyboards, and PC peripherals'],
            ['name' => 'IBM',               'classification' => 'Tech',            'description' => 'Enterprise computing, storage, and IT infrastructure'],
            ['name' => 'ICLEVER',           'classification' => 'Design/Consumer', 'description' => 'Wireless keyboards, mice, and mobile accessories'],
            ['name' => 'IFIXIT',            'classification' => 'Tech',            'description' => 'Repair tools, kits, and electronics maintenance supplies'],
            ['name' => 'IHOME',             'classification' => 'Tech',            'description' => 'Alarm clocks, speakers, and smart home accessories'],
            ['name' => 'IKKO',              'classification' => 'Both',            'description' => 'In-ear monitors and audiophile earphones'],
            ['name' => 'ILFORD',            'classification' => 'Design/Consumer', 'description' => 'Black and white photographic film and darkroom paper'],
            ['name' => 'IMUTO',             'classification' => 'Tech',            'description' => 'Power banks and portable charging accessories'],
            ['name' => 'INATECK',           'classification' => 'Tech',            'description' => 'USB hubs, PC card readers, and laptop sleeves'],
            ['name' => 'INGCO',             'classification' => 'Tech',            'description' => 'Power tools, hand tools, and hardware equipment'],
            ['name' => 'INSTA360',          'classification' => 'Design/Consumer', 'description' => '360° and action cameras for immersive content'],
            ['name' => 'INSTAX',            'classification' => 'Design/Consumer', 'description' => 'Fujifilm instant cameras and film cartridges'],
            ['name' => 'INTEX',             'classification' => 'Design/Consumer', 'description' => 'Inflatable products and consumer electronics'],
            ['name' => 'JBL',               'classification' => 'Design/Consumer', 'description' => 'Speakers, headphones, and professional audio gear'],
            ['name' => 'JEIFN',             'classification' => 'Tech',            'description' => 'Camera cage accessories and video production mounts'],
            ['name' => 'JLAB',              'classification' => 'Tech',            'description' => 'Affordable wireless earbuds and headphones'],
            ['name' => 'JOBY',              'classification' => 'Tech',            'description' => 'GorillaPod flexible tripods and content creator rigs'],
            ['name' => 'JTECH',             'classification' => 'Tech',            'description' => 'Ergonomic keyboards and wireless desk accessories'],
            ['name' => 'JVC',               'classification' => 'Tech',            'description' => 'Camcorders, headphones, and consumer electronics'],
            ['name' => 'K&F',               'classification' => 'Both',            'description' => 'Camera filters, lens adapters, and photography accessories'],
            ['name' => 'KALA',              'classification' => 'Design/Consumer', 'description' => 'Ukuleles and string instruments for all levels'],
            ['name' => 'KANO',              'classification' => 'Tech',            'description' => 'Educational coding kits and tech learning tools'],
            ['name' => 'KENKO',             'classification' => 'Both',            'description' => 'Camera filters, teleconverters, and optical accessories'],
            ['name' => 'KENTMERE',          'classification' => 'Design/Consumer', 'description' => 'Affordable black and white photographic film'],
            ['name' => 'KEVLER',            'classification' => 'Both',            'description' => 'Professional PA amplifiers and audio equipment'],
            ['name' => 'KEYCHRON',          'classification' => 'Design/Consumer', 'description' => 'Mechanical keyboards for Mac and Windows users'],
            ['name' => 'KICA',              'classification' => 'Design/Consumer', 'description' => 'Portable electric fans and cooling accessories'],
            ['name' => 'KODAK',             'classification' => 'Design/Consumer', 'description' => 'Film photography, instant cameras, and imaging products'],
            ['name' => 'KONZERT',           'classification' => 'Both',            'description' => 'PA systems, mixers, and audio equipment'],
            ['name' => 'KRK',               'classification' => 'Tech',            'description' => 'Studio monitor speakers for mixing and mastering'],
            ['name' => 'LANEY',             'classification' => 'Design/Consumer', 'description' => 'Guitar and bass amplifiers for stage and studio'],
            ['name' => 'LED',               'classification' => 'Both',            'description' => 'LED lighting solutions and fixtures'],
            ['name' => 'LEDUS',             'classification' => 'Both',            'description' => 'LED studio lights and photography lighting'],
            ['name' => 'LEXAR',             'classification' => 'Tech',            'description' => 'Memory cards, SSDs, and flash storage solutions'],
            ['name' => 'LG',                'classification' => 'Both',            'description' => 'TVs, monitors, smartphones, and home appliances'],
            ['name' => 'LOGICOWL',          'classification' => 'Tech',            'description' => 'Wireless camera remotes and intervalometers'],
            ['name' => 'LOGITECH',          'classification' => 'Design/Consumer', 'description' => 'Webcams, peripherals, speakers, and streaming accessories'],
            ['name' => 'LOUPEDECK',         'classification' => 'Design/Consumer', 'description' => 'Creative editing consoles for photo and video workflows'],
            ['name' => 'LOWEPRO',           'classification' => 'Both',            'description' => 'Camera bags, backpacks, and protective carry solutions'],
            ['name' => 'LUDWIG',            'classification' => 'Design/Consumer', 'description' => 'Drum kits, snare drums, and percussion instruments'],
            ['name' => 'LUXCEO',            'classification' => 'Tech',            'description' => 'Portable RGB LED lights for video and photography'],
            ['name' => 'M-AUDIO',           'classification' => 'Tech',            'description' => 'MIDI controllers, audio interfaces, and studio monitors'],
            ['name' => 'MACALLY',           'classification' => 'Design/Consumer', 'description' => 'Mac-compatible keyboards, mice, and accessories'],
            ['name' => 'MAHALO',            'classification' => 'Design/Consumer', 'description' => 'Beginner ukuleles and affordable string instruments'],
            ['name' => 'MANFROTTO',         'classification' => 'Tech',            'description' => 'Professional tripods, heads, and camera support systems'],
            ['name' => 'MAONO',             'classification' => 'Tech',            'description' => 'USB microphones and podcasting audio equipment'],
            ['name' => 'MARSHALL',          'classification' => 'Design/Consumer', 'description' => 'Iconic guitar amplifiers and portable Bluetooth speakers'],
            ['name' => 'MARTIN',            'classification' => 'Both',            'description' => 'Handcrafted acoustic guitars and guitar strings'],
            ['name' => 'MARTIN AUDIO',      'classification' => 'Design/Consumer', 'description' => 'Professional line array and PA loudspeaker systems'],
            ['name' => 'MATADOR',           'classification' => 'Design/Consumer', 'description' => 'Travel gear, packable bags, and outdoor accessories'],
            ['name' => 'MEDALIGHT',         'classification' => 'Both',            'description' => 'On-camera LED video lights and ring lights'],
            ['name' => 'MEFOTO',            'classification' => 'Tech',            'description' => 'Travel tripods and camera support accessories'],
            ['name' => 'MEIKE',             'classification' => 'Both',            'description' => 'Camera battery grips, lenses, and accessories'],
            ['name' => 'MEKING',            'classification' => 'Tech',            'description' => 'Photography studio lights and softbox kits'],
            ['name' => 'MOBIL 1',           'classification' => 'Both',            'description' => 'Motor oils and vehicle lubrication products'],
            ['name' => 'MOOV',              'classification' => 'Design/Consumer', 'description' => 'Smart fitness trackers and activity monitoring bands'],
            ['name' => 'MOUNT-IT',          'classification' => 'Both',            'description' => 'Monitor mounts, TV wall mounts, and desk stands'],
            ['name' => 'MOZA',              'classification' => 'Design/Consumer', 'description' => 'Camera gimbals and stabilizers for film and content'],
            ['name' => 'MTIAN',             'classification' => 'Tech',            'description' => 'Photography accessories and lighting modifiers'],
            ['name' => 'NANLITE',           'classification' => 'Both',            'description' => 'LED studio and portable lighting for film and photography'],
            ['name' => 'NEEWER',            'classification' => 'Design/Consumer', 'description' => 'Camera accessories, lighting kits, and studio equipment'],
            ['name' => 'NIKON',             'classification' => 'Both',            'description' => 'Cameras, optics, and precision imaging instruments'],
            ['name' => 'NORTH BAYOU',       'classification' => 'Design/Consumer', 'description' => 'Monitor arms and adjustable desk mounts'],
            ['name' => 'NOVATION',          'classification' => 'Design/Consumer', 'description' => 'MIDI keyboards, controllers, and music production tools'],
            ['name' => 'NOYAFA',            'classification' => 'Tech',            'description' => 'Network cable testers and professional wiring tools'],
            ['name' => 'NUMARK',            'classification' => 'Tech',            'description' => 'DJ controllers, turntables, and mixing equipment'],
            ['name' => 'OBSBOT',            'classification' => 'Design/Consumer', 'description' => 'AI-powered auto-tracking webcams and cameras'],
            ['name' => 'OC ACOUSTIC',       'classification' => 'Design/Consumer', 'description' => 'Classical and acoustic guitars for students and players'],
            ['name' => 'OHUHU',             'classification' => 'Design/Consumer', 'description' => 'Art supplies, ring lights, and creative accessories'],
            ['name' => 'OLYMPUS',           'classification' => 'Both',            'description' => 'Cameras, lenses, and digital imaging equipment'],
            ['name' => 'OMNI',              'classification' => 'Tech',            'description' => 'Photography accessories and studio equipment'],
            ['name' => 'ONEODIO',           'classification' => 'Design/Consumer', 'description' => 'Studio monitor headphones and DJ headphones'],
            ['name' => 'OPENROCK',          'classification' => 'Design/Consumer', 'description' => 'Open-ear sport earphones and wireless audio'],
            ['name' => 'ORANGE',            'classification' => 'Design/Consumer', 'description' => 'Guitar and bass amplifiers with iconic British tone'],
            ['name' => 'ORICO',             'classification' => 'Both',            'description' => 'USB hubs, hard drive enclosures, and storage accessories'],
            ['name' => 'PANASONIC',         'classification' => 'Both',            'description' => 'Cameras, video equipment, and consumer electronics'],
            ['name' => 'PEAK DESIGN',       'classification' => 'Design/Consumer', 'description' => 'Camera straps, bags, and premium carry accessories'],
            ['name' => 'PEAKMETER',         'classification' => 'Tech',            'description' => 'Digital multimeters and electrical testing equipment'],
            ['name' => 'PEARL',             'classification' => 'Design/Consumer', 'description' => 'Drum kits, hardware, and percussion instruments'],
            ['name' => 'PELICAN',           'classification' => 'Tech',            'description' => 'Protective hard cases for cameras and sensitive equipment'],
            ['name' => 'PGYTECH',           'classification' => 'Both',            'description' => 'Drone accessories, bags, and camera carry solutions'],
            ['name' => 'PHONE HOLDER',      'classification' => 'Both',            'description' => 'Universal phone mounts and holder accessories'],
            ['name' => 'PHOTOOLEX',         'classification' => 'Tech',            'description' => 'Camera remote shutter triggers and accessories'],
            ['name' => 'PHOTTIX',           'classification' => 'Design/Consumer', 'description' => 'Flash triggers, studio strobes, and lighting accessories'],
            ['name' => 'PIKXI',             'classification' => 'Design/Consumer', 'description' => 'Photography accessories and creative gear'],
            ['name' => 'PLANET WAVE',       'classification' => 'Design/Consumer', 'description' => 'Guitar straps, cables, and musician accessories'],
            ['name' => 'PMI',               'classification' => 'Design/Consumer', 'description' => 'Professional audio and PA equipment'],
            ['name' => 'PORTKEYS',          'classification' => 'Tech',            'description' => 'On-camera monitors and director\'s viewfinders'],
            ['name' => 'PRO-LOK',           'classification' => 'Both',            'description' => 'Professional locksmith tools and security equipment'],
            ['name' => 'PROEL',             'classification' => 'Both',            'description' => 'Professional audio equipment and PA systems'],
            ['name' => 'PXEL',              'classification' => 'Tech',            'description' => 'Photography accessories and studio lighting'],
            ['name' => 'PXN',               'classification' => 'Design/Consumer', 'description' => 'Gaming controllers and mobile game accessories'],
            ['name' => 'QSC',               'classification' => 'Tech',            'description' => 'Professional power amplifiers and PA system components'],
            ['name' => 'RADIAL',            'classification' => 'Both',            'description' => 'Direct boxes, splitters, and professional audio tools'],
            ['name' => 'RAPTOR',            'classification' => 'Tech',            'description' => 'Camera bags and photography carrying solutions'],
            ['name' => 'RAVPOWER',          'classification' => 'Both',            'description' => 'Power banks, chargers, and wireless charging accessories'],
            ['name' => 'RAZER',             'classification' => 'Design/Consumer', 'description' => 'Gaming peripherals, laptops, and streaming gear'],
            ['name' => 'REDRAGON',          'classification' => 'Design/Consumer', 'description' => 'Gaming keyboards, mice, and affordable peripherals'],
            ['name' => 'REMO',              'classification' => 'Design/Consumer', 'description' => 'Drum heads, drumheads, and percussion accessories'],
            ['name' => 'RODE',              'classification' => 'Both',            'description' => 'Professional microphones for film, broadcast, and podcasting'],
            ['name' => 'ROYAL KLUDGE',      'classification' => 'Design/Consumer', 'description' => 'Mechanical keyboards and wireless typing accessories'],
            ['name' => 'SAIREN',            'classification' => 'Design/Consumer', 'description' => 'Wireless lavalier microphones and video audio gear'],
            ['name' => 'SAKURA',            'classification' => 'Design/Consumer', 'description' => 'Art markers, pens, and illustration supplies'],
            ['name' => 'SAMSON',            'classification' => 'Tech',            'description' => 'Microphones, headphones, and audio monitoring gear'],
            ['name' => 'SAMSUNG',           'classification' => 'Both',            'description' => 'Cameras, storage, smartphones, and consumer electronics'],
            ['name' => 'SAMYANG',           'classification' => 'Both',            'description' => 'Manual and auto-focus lenses for photo and video'],
            ['name' => 'SANDISK',           'classification' => 'Both',            'description' => 'Memory cards, flash drives, and portable SSDs'],
            ['name' => 'SARAMONIC',         'classification' => 'Both',            'description' => 'Wireless microphone systems and video audio gear'],
            ['name' => 'SEKONIC',           'classification' => 'Tech',            'description' => 'Light meters and exposure measurement tools'],
            ['name' => 'SENNHEISER',        'classification' => 'Design/Consumer', 'description' => 'Premium headphones, microphones, and wireless audio'],
            ['name' => 'SHURE',             'classification' => 'Both',            'description' => 'Professional microphones, headphones, and wireless systems'],
            ['name' => 'SIGMA',             'classification' => 'Both',            'description' => 'High-quality lenses and mirrorless cameras'],
            ['name' => 'SIMORR',            'classification' => 'Design/Consumer', 'description' => 'Camera accessories, LED lights, and video production gear'],
            ['name' => 'SIRUI',             'classification' => 'Tech',            'description' => 'Tripods, monopods, and precision camera support systems'],
            ['name' => 'SJCAM',             'classification' => 'Design/Consumer', 'description' => 'Action cameras and sports video recording accessories'],
            ['name' => 'SKULL CANDY',       'classification' => 'Design/Consumer', 'description' => 'Lifestyle headphones and earphones for active users'],
            ['name' => 'SMALLRIG',          'classification' => 'Both',            'description' => 'Camera cages, rigs, and production accessories'],
            ['name' => 'SMART SENSOR',      'classification' => 'Both',            'description' => 'Digital measuring instruments and environmental sensors'],
            ['name' => 'SMEG',              'classification' => 'Both',            'description' => 'Retro-styled kitchen appliances and home electronics'],
            ['name' => 'SNDWAY',            'classification' => 'Tech',            'description' => 'Laser distance meters and measurement tools'],
            ['name' => 'SONGDIAN',          'classification' => 'Design/Consumer', 'description' => 'Camera batteries and power accessories for photographers'],
            ['name' => 'SONY',              'classification' => 'Both',            'description' => 'Consumer electronics, cameras, and imaging solutions'],
            ['name' => 'SP-PRES',           'classification' => 'Both',            'description' => 'Speaker stands and PA hardware accessories'],
            ['name' => 'SPER',              'classification' => 'Both',            'description' => 'Scientific measurement and environmental testing instruments'],
            ['name' => 'SQUIER',            'classification' => 'Design/Consumer', 'description' => 'Entry-level Fender-designed guitars and basses'],
            ['name' => 'SSL',               'classification' => 'Both',            'description' => 'Professional audio mixing consoles and interfaces'],
            ['name' => 'STANLEY',           'classification' => 'Design/Consumer', 'description' => 'Hand tools, storage solutions, and hardware equipment'],
            ['name' => 'STEINBERG',         'classification' => 'Tech',            'description' => 'DAW software, audio interfaces, and music production tools'],
            ['name' => 'SUNSUN',            'classification' => 'Both',            'description' => 'Aquarium and pond equipment and accessories'],
            ['name' => 'SURELOCK',          'classification' => 'Both',            'description' => 'Security locks and safety equipment'],
            ['name' => 'TAKAMINE',          'classification' => 'Design/Consumer', 'description' => 'Acoustic and semi-acoustic guitars for performers'],
            ['name' => 'TAMRON',            'classification' => 'Both',            'description' => 'Versatile zoom and prime lenses for major camera mounts'],
            ['name' => 'TAOTRONICS',        'classification' => 'Both',            'description' => 'Wireless earbuds, LED lights, and consumer electronics'],
            ['name' => 'TASCAM',            'classification' => 'Both',            'description' => 'Portable audio recorders and studio recording equipment'],
            ['name' => 'TASI',              'classification' => 'Both',            'description' => 'Digital measurement tools and environmental instruments'],
            ['name' => 'TELESIN',           'classification' => 'Design/Consumer', 'description' => 'Action camera accessories and GoPro mounts'],
            ['name' => 'TENVEO',            'classification' => 'Design/Consumer', 'description' => 'PTZ cameras and video conferencing solutions'],
            ['name' => 'TERIS',             'classification' => 'Tech',            'description' => 'Camera cage accessories and video production rigs'],
            ['name' => 'THERMOPRO',         'classification' => 'Tech',            'description' => 'Digital thermometers and food temperature measurement'],
            ['name' => 'THINKTANK',         'classification' => 'Both',            'description' => 'Premium camera bags and rolling cases for professionals'],
            ['name' => 'TOTU',              'classification' => 'Both',            'description' => 'USB hubs, docking stations, and mobile accessories'],
            ['name' => 'TP-LINK',           'classification' => 'Tech',            'description' => 'Networking equipment, routers, and Wi-Fi accessories'],
            ['name' => 'TRIBIT',            'classification' => 'Tech',            'description' => 'Bluetooth speakers and wireless audio devices'],
            ['name' => 'TRIOPO',            'classification' => 'Both',            'description' => 'Photography lighting accessories, softboxes, and tripods'],
            ['name' => 'TTARTISAN',         'classification' => 'Both',            'description' => 'Manual lenses and cinema glass for mirrorless cameras'],
            ['name' => 'U-SELECT',          'classification' => 'Both',            'description' => 'USB switches and peripheral sharing devices'],
            ['name' => 'UCASSA',            'classification' => 'Design/Consumer', 'description' => 'Photography accessories and camera creative tools'],
            ['name' => 'UGREEN',            'classification' => 'Design/Consumer', 'description' => 'Cables, hubs, chargers, and connectivity accessories'],
            ['name' => 'ULANZI',            'classification' => 'Design/Consumer', 'description' => 'Camera accessories, lens attachments, and creator tools'],
            ['name' => 'UURIG',             'classification' => 'Design/Consumer', 'description' => 'Camera cage accessories and cold shoe mounts'],
            ['name' => 'VENTION',           'classification' => 'Tech',            'description' => 'Cables, audio accessories, and connectivity solutions'],
            ['name' => 'VIC FIRTH',         'classification' => 'Design/Consumer', 'description' => 'Drumsticks, mallets, and percussion accessories'],
            ['name' => 'VIEWSONIC',         'classification' => 'Tech',            'description' => 'Monitors, projectors, and display solutions'],
            ['name' => 'VIJIM',             'classification' => 'Design/Consumer', 'description' => 'Portable LED video lights and flexible gorilla stands'],
            ['name' => 'VILTROX',           'classification' => 'Both',            'description' => 'Auto-focus lenses, speedlights, and camera accessories'],
            ['name' => 'VSGO',              'classification' => 'Design/Consumer', 'description' => 'Camera sensor cleaning kits and maintenance tools'],
            ['name' => 'WASABI POWER',      'classification' => 'Tech',            'description' => 'Replacement camera batteries and dual chargers'],
            ['name' => 'WD',                'classification' => 'Design/Consumer', 'description' => 'Hard drives, SSDs, and portable storage solutions'],
            ['name' => 'WEIFENG',           'classification' => 'Tech',            'description' => 'Tripods and camera support equipment'],
            ['name' => 'WESTCOTT',          'classification' => 'Both',            'description' => 'Photography lighting, softboxes, and light modifiers'],
            ['name' => 'WINTACT',           'classification' => 'Both',            'description' => 'Digital measurement instruments and detection tools'],
            ['name' => 'WLN',               'classification' => 'Tech',            'description' => 'Compact walkie-talkies and two-way radios'],
            ['name' => 'XP-PEN',            'classification' => 'Design/Consumer', 'description' => 'Drawing tablets and pen displays for digital artists'],
            ['name' => 'YAMAHA',            'classification' => 'Design/Consumer', 'description' => 'Musical instruments, mixers, and professional audio'],
            ['name' => 'YASHICA',           'classification' => 'Design/Consumer', 'description' => 'Film and digital cameras with retro aesthetic'],
            ['name' => 'YC ONION',          'classification' => 'Both',            'description' => 'Compact LED lights and photography accessories'],
            ['name' => 'YOLOLIV',           'classification' => 'Tech',            'description' => 'Live streaming encoders and production equipment'],
            ['name' => 'YONGNUO',           'classification' => 'Both',            'description' => 'Flash units, triggers, and LED video lighting'],
            ['name' => 'YOOBAO',            'classification' => 'Design/Consumer', 'description' => 'Power banks and mobile charging accessories'],
            ['name' => 'ZGCINE',            'classification' => 'Both',            'description' => 'V-mount batteries and power solutions for video production'],
            ['name' => 'ZHIYUN',            'classification' => 'Both',            'description' => 'Camera and smartphone gimbals and stabilizers'],
            ['name' => 'ZILDJIAN',          'classification' => 'Design/Consumer', 'description' => 'Cymbals, drumsticks, and percussion accessories'],
            ['name' => 'ZITAY',             'classification' => 'Tech',            'description' => 'V-mount battery adapters and power accessories'],
            ['name' => 'ZOMEI',             'classification' => 'Design/Consumer', 'description' => 'Photography filters, tripods, and studio accessories'],
            ['name' => 'ZOOM',              'classification' => 'Design/Consumer', 'description' => 'Portable audio recorders, interfaces, and effects pedals'],
        ];

        Brand::insert($brands);
    }
}
