<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            ['name' => 'Sony',                'description' => 'Consumer electronics, cameras, and imaging solutions'],
            ['name' => 'Canon',               'description' => 'Cameras, lenses, and professional imaging equipment'],
            ['name' => 'Nikon',               'description' => 'Cameras, optics, and precision imaging instruments'],
            ['name' => 'Insta360',            'description' => '360° and action cameras for immersive content'],
            ['name' => 'GoPro',               'description' => 'Rugged action cameras and mounting accessories'],
            ['name' => 'Kodak',               'description' => 'Film photography and consumer camera products'],
            ['name' => 'Fujifilm',            'description' => 'Cameras, instant film, and professional imaging'],
            ['name' => 'Panasonic',           'description' => 'Cameras, video equipment, and consumer electronics'],
            ['name' => '7artisans',           'description' => 'Affordable manual prime lenses for mirrorless cameras'],
            ['name' => 'Acasis',              'description' => 'USB hubs, docking stations, and storage accessories'],
            ['name' => 'Accsoon',             'description' => 'Wireless video transmission systems for filmmakers'],
            ['name' => 'Alto Professional',   'description' => 'Powered PA speakers and audio mixers'],
            ['name' => 'Aputure',             'description' => 'Professional LED lighting for film and photography'],
            ['name' => 'audio-technica',      'description' => 'Professional microphones, headphones, and audio gear'],
            ['name' => 'AVMATRIX',            'description' => 'Video switchers, scalers, and production equipment'],
            ['name' => 'Behringer',           'description' => 'Audio mixers, interfaces, and studio equipment'],
            ['name' => 'BENRO',               'description' => 'Tripods, monopods, and camera support systems'],
            ['name' => 'Blackmagic Design',   'description' => 'Cinema cameras, video production, and color grading tools'],
            ['name' => 'brinno',              'description' => 'Time-lapse and construction site cameras'],
            ['name' => 'CAME-TV',             'description' => 'Camera gimbals, sliders, and production support gear'],
            ['name' => 'CASIO',               'description' => 'Compact cameras and electronic instruments'],
            ['name' => 'Creative',            'description' => 'Sound cards, USB speakers, and PC audio gear'],
            ['name' => 'Crown',               'description' => 'Professional power amplifiers for live sound'],
            ['name' => 'Datacolor',           'description' => 'Color calibration tools and monitor profiling devices'],
            ['name' => 'Desview',             'description' => 'On-camera field monitors for video production'],
            ['name' => 'DJI',                 'description' => 'Drones, gimbals, and aerial imaging systems'],
            ['name' => 'EBL',                 'description' => 'Rechargeable batteries and smart chargers'],
            ['name' => 'ECOFLOW',             'description' => 'Portable power stations and solar charging solutions'],
            ['name' => 'Eirmai',              'description' => 'Camera bags, dry cabinets, and storage solutions'],
            ['name' => 'eneloop',             'description' => 'High-performance rechargeable AA and AAA batteries'],
            ['name' => 'Epiphone',            'description' => 'Electric and acoustic guitars and bass guitars'],
            ['name' => 'EPSON',               'description' => 'Photo printers, projectors, and imaging devices'],
            ['name' => 'FeelWorld',           'description' => 'Field monitors and camera monitors for video work'],
            ['name' => 'FeiyuTech',           'description' => 'Camera gimbals and stabilizers for photo and video'],
            ['name' => 'fifine',              'description' => 'USB and XLR microphones for streaming and podcasting'],
            ['name' => 'Focusrite',           'description' => 'Audio interfaces and studio recording equipment'],
            ['name' => 'Fujitsu',             'description' => 'Storage solutions and enterprise electronics'],
            ['name' => 'Godox',               'description' => 'Studio flash, speedlights, and LED video lighting'],
            ['name' => 'Harman/Kardon',       'description' => 'Premium Bluetooth and home audio speakers'],
            ['name' => 'Hercules Stands',     'description' => 'Guitar, keyboard, and instrument stands'],
            ['name' => 'hohem',               'description' => 'Smartphone and camera gimbals for stable footage'],
            ['name' => 'HOLLYLAND',           'description' => 'Wireless video and intercom communication systems'],
            ['name' => 'ILFORD',              'description' => 'Black and white photographic film and paper'],
            ['name' => 'instax',              'description' => 'Fujifilm instant cameras and film'],
            ['name' => 'JBL',                 'description' => 'Speakers, headphones, and professional audio gear'],
            ['name' => 'Joby',                'description' => 'GorillaPod flexible tripods and content creator rigs'],
            ['name' => 'K&F Concept',         'description' => 'Camera filters, lens adapters, and photography accessories'],
            ['name' => 'Kentmere',            'description' => 'Affordable black and white photographic film'],
            ['name' => 'Kevler Professional', 'description' => 'Professional PA amplifiers and audio equipment'],
            ['name' => 'Konzert',             'description' => 'PA systems, mixers, and audio equipment'],
            ['name' => 'KRK Systems',         'description' => 'Studio monitor speakers for mixing and mastering'],
            ['name' => 'Laney',               'description' => 'Guitar and bass amplifiers for stage and studio'],
            ['name' => 'Lexar',               'description' => 'Memory cards, SSDs, and flash storage solutions'],
            ['name' => 'LogicOwl',            'description' => 'Wireless camera remotes and intervalometers'],
            ['name' => 'Logitech',            'description' => 'Webcams, peripherals, and streaming accessories'],
            ['name' => 'Lowepro',             'description' => 'Camera bags, backpacks, and protective cases'],
            ['name' => 'Manfrotto',           'description' => 'Professional tripods, heads, and camera support systems'],
            ['name' => 'maono',               'description' => 'USB microphones and podcasting audio equipment'],
            ['name' => 'Marshal',             'description' => 'Guitar amplifiers and speaker cabinets'],
            ['name' => 'Meke',                'description' => 'Macro and cine lenses for mirrorless cameras'],
            ['name' => 'Nanlite',             'description' => 'LED studio and portable lighting for photography and film'],
            ['name' => 'Neewer',              'description' => 'Camera accessories, lighting, and studio equipment'],
            ['name' => 'NIB',                 'description' => 'Camera accessories and photography gear'],
            ['name' => 'Nofaya',              'description' => 'Camera straps and carrying accessories'],
            ['name' => 'Obsbot',              'description' => 'AI-powered auto-tracking webcams and cameras'],
            ['name' => 'OMNI',                'description' => 'Photography accessories and studio equipment'],
            ['name' => 'OneOdio',             'description' => 'Studio monitor headphones and DJ headphones'],
            ['name' => 'Orange',              'description' => 'Guitar and bass amplifiers known for iconic tone'],
            ['name' => 'Orico',               'description' => 'USB hubs, hard drive enclosures, and storage accessories'],
            ['name' => 'Pearl',               'description' => 'Drums, percussion, and hardware for drummers'],
            ['name' => 'Pelican',             'description' => 'Protective hard cases for cameras and sensitive gear'],
            ['name' => 'PGYTECH',             'description' => 'Drone accessories and camera carrying solutions'],
            ['name' => 'Phottix',             'description' => 'Flash triggers, studio strobes, and lighting accessories'],
            ['name' => 'Pikxi',               'description' => 'Photography accessories and creative gear'],
            ['name' => 'Pxel',                'description' => 'Photography accessories and studio lighting'],
            ['name' => 'PXN',                 'description' => 'Gaming controllers and mobile game accessories'],
            ['name' => 'Raptor',              'description' => 'Camera bags and photography carrying solutions'],
            ['name' => 'RavPower',            'description' => 'Portable chargers, power banks, and charging accessories'],
            ['name' => 'Rode',                'description' => 'Professional microphones for film, broadcast, and podcasting'],
            ['name' => 'Samson',              'description' => 'Microphones, headphones, and audio monitoring gear'],
            ['name' => 'Samyang',             'description' => 'Manual and auto-focus lenses for photo and video'],
            ['name' => 'SanDisk',             'description' => 'Memory cards, flash drives, and portable SSDs'],
            ['name' => 'Sigma',               'description' => 'High-quality lenses and mirrorless cameras'],
            ['name' => 'SmallRig',            'description' => 'Camera cages, rigs, and production accessories'],
            ['name' => 'Tamron',              'description' => 'Versatile zoom and prime lenses for major mounts'],
            ['name' => 'Tenveo',              'description' => 'PTZ cameras and video conferencing solutions'],
            ['name' => 'thinktank',           'description' => 'Premium camera bags and rolling cases for professionals'],
            ['name' => 'TP-Link',             'description' => 'Networking equipment, routers, and Wi-Fi accessories'],
            ['name' => 'Triopo',              'description' => 'Photography lighting accessories and softboxes'],
            ['name' => 'Ugreen',              'description' => 'Cables, hubs, and charging accessories'],
            ['name' => 'Ulanzi',              'description' => 'Camera accessories, lens attachments, and creator tools'],
            ['name' => 'Vention',             'description' => 'Cables, audio accessories, and connectivity solutions'],
            ['name' => 'Vic Firth',           'description' => 'Drumsticks, mallets, and percussion accessories'],
            ['name' => 'Viltrox',             'description' => 'Auto-focus lenses and camera accessories'],
            ['name' => 'VSGO',                'description' => 'Camera sensor cleaning kits and maintenance tools'],
            ['name' => 'Wasabi Power',        'description' => 'Replacement camera batteries and chargers'],
            ['name' => 'Western Digital',     'description' => 'Hard drives, SSDs, and portable storage solutions'],
            ['name' => 'Weifeng',             'description' => 'Tripods and camera support equipment'],
            ['name' => 'Yamaha',              'description' => 'Musical instruments, mixers, and professional audio'],
            ['name' => 'Yololiv',             'description' => 'Live streaming encoders and production equipment'],
            ['name' => 'Yongnuo',             'description' => 'Flash units, triggers, and LED video lighting'],
            ['name' => 'Yoobao',              'description' => 'Power banks and mobile charging accessories'],
            ['name' => 'Zhiyun',              'description' => 'Camera and smartphone gimbals and stabilizers'],
            ['name' => 'Zildjian',            'description' => 'Cymbals and drumsticks for drummers'],
            ['name' => 'Zomei',               'description' => 'Photography filters, tripods, and studio accessories'],
            ['name' => 'Zoom',                'description' => 'Portable audio recorders, interfaces, and effects pedals'],
        ];

        foreach ($brands as $brand) {
            Brand::firstOrCreate(['name' => $brand['name']], ['description' => $brand['description']]);
        }
    }
}
